// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/register": {
            "post": {
                "description": "Register a new user with phone/email and password",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "User Registration",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Login with phone/email and password",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh access token using refresh token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh token request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/v1/positions": {
            "get": {
                "description": "Get paginated list of positions with filters",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Position"],
                "summary": "Get Position List",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer", "description": "Page number"},
                    {"name": "page_size", "in": "query", "type": "integer", "description": "Page size"},
                    {"name": "exam_type", "in": "query", "type": "string", "description": "Exam type filter"},
                    {"name": "province", "in": "query", "type": "string", "description": "Province code"},
                    {"name": "education", "in": "query", "type": "string", "description": "Education level"},
                    {"name": "keyword", "in": "query", "type": "string", "description": "Search keyword"}
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/v1/positions/{id}": {
            "get": {
                "description": "Get detailed information of a position",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Position"],
                "summary": "Get Position Detail",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer", "description": "Position ID"}
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Response"
                        }
                    }
                }
            }
        },
        "/api/v1/positions/{id}/favorite": {
            "post": {
                "security": [{"Bearer": []}],
                "description": "Add a position to user's favorites",
                "tags": ["Position"],
                "summary": "Add Favorite",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            },
            "delete": {
                "security": [{"Bearer": []}],
                "description": "Remove a position from user's favorites",
                "tags": ["Position"],
                "summary": "Remove Favorite",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get current user profile",
                "tags": ["User"],
                "summary": "Get User Profile",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            },
            "put": {
                "security": [{"Bearer": []}],
                "description": "Update current user profile",
                "tags": ["User"],
                "summary": "Update User Profile",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            }
        },
        "/api/v1/match/positions": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get positions matched to user profile",
                "tags": ["Match"],
                "summary": "Get Matched Positions",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            }
        },
        "/api/v1/announcements": {
            "get": {
                "description": "Get paginated list of announcements",
                "tags": ["Announcement"],
                "summary": "Get Announcement List",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer"},
                    {"name": "page_size", "in": "query", "type": "integer"},
                    {"name": "exam_type", "in": "query", "type": "string"}
                ],
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            }
        },
        "/api/v1/notifications": {
            "get": {
                "security": [{"Bearer": []}],
                "description": "Get user notifications",
                "tags": ["Notification"],
                "summary": "Get Notifications",
                "responses": {
                    "200": {"description": "OK", "schema": {"$ref": "#/definitions/Response"}}
                }
            }
        }
    },
    "definitions": {
        "Response": {
            "type": "object",
            "properties": {
                "code": {"type": "integer"},
                "message": {"type": "string"},
                "data": {"type": "object"}
            }
        },
        "RegisterRequest": {
            "type": "object",
            "properties": {
                "phone": {"type": "string"},
                "email": {"type": "string"},
                "password": {"type": "string"},
                "nickname": {"type": "string"}
            }
        },
        "LoginRequest": {
            "type": "object",
            "properties": {
                "account": {"type": "string"},
                "password": {"type": "string"}
            }
        },
        "RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {"type": "string"}
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter the token with the 'Bearer ' prefix, e.g. 'Bearer abcde12345'"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "公考职位智能筛选系统 API",
	Description:      "公考职位智能筛选系统后端API接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
